### ISSUE TITLE
Fahrzeuge

### ISSUE THREAD

**Issue by eGGad1991** [Aquanetic/PublicEnemy-Bugs#11]
bin gestorben Fahrzeug habe ich stehen lassen, am nächsten Tag eingeloggt : Fahrzeug ist weder in der Garage noch am Abschlepphof

**Comment by Aquanetic** [comment]
Bei den Fahrzeugen kann es dazu kommen, das diese an der alten Position stehen bleiben wo sie zu letzt waren (Ohne Server neustart). Beispiel: Ich bin mit einem Helikopter zum Diamon Casino geflogen und habe den dort abgestellt ca 2 Tage später stand er immer noch da

pls Verifizieren

**Comment by Guiseppe-Morello** [comment]
ja kann ich so bestägigen mit perristente fahrzeuge

**Comment by Guiseppe-Morello** [comment]
ok fahrzeuge doch nicht peristent gehen von aus das man es mindestens einmal eingepark haben muss das es in die letzte garage muss muss man nochmal testen
