### ISSUE TITLE
Krankenhaus 

### ISSUE THREAD

**Issue by eGGad1991** [Aquanetic/PublicEnemy-Bugs#13]
Ist zwar bekannt aber das das Krankenhaus nicht da ist spawnt man im Untergrund im Bahn Tunnel

**Comment by Aquanetic** [comment]
https://github.com/Aquanetic/PublicEnemy-Bugs/issues/10#issue-1123133032

Upgrade sollte dieses Wochenende direkt kommen Neues Pillbox ist geplant

**Comment by Aquanetic** [comment]
Wird nach Update geschlossen

**Comment by Guiseppe-Morello** [comment]
geht nun auch
