### ISSUE TITLE
Handy

### ISSUE THREAD

**Issue by Eggad** [Aquanetic/PublicEnemy-Bugs#4]
Anrufe funktionieren nicht und bei Verlust kann man sich leider kein neues holen

**Comment by Aquanetic** [comment]
Anrufe müssen noch mit Salty Chat kompatibel geschaltet werden ... Leider etwas schwer wegen dem QB Framework aber ist in Arbeit

Ich Splitte den Issue in 2 Teile 
Telefon über Salty & Handy Kaufen
