### ISSUE TITLE
CHar verletzt schon bei char erstellung

### ISSUE THREAD

**Issue by Guiseppe-Morello** [Aquanetic/PublicEnemy-Bugs#9]
Bin Zum Char erstellen eingeloggt. Schon in der Einstellmöglichkeit mit Name und Geburtsdatum. Stand halt das ich verletzt bin und ausblute in x Sekunden. Nun Bin ich ausgeblutet kann. Mein Char weiterbearbeiten Aber da er am Boden liegt kann ich den Char nur bedingt sehen. Um zusehen wie mein Char nun wirklich aussieht. Und Respawn geht nicht solange die Einstellungen noch nicht gemacht sind.

**Comment by Aquanetic** [comment]
Charaktere sollte sich nicht selbst verletzten während der Erstellung.
Könnte ein einmaliger Fehler gewesen sein.
